"""The generator for `REGISTER.md` — the suite as a numbered, categorised projection.

**The page is a projection, not a summary.** Its numbers come from a real collection and its
descriptions are the first line of each test file's own docstring, so nothing in it is a second
copy of the truth that could drift from the first. `tests/test_register.py` re-derives both and
fails when the committed page disagrees, which is what makes "regenerate, do not edit" a fact
rather than an instruction.

This module is not collected by pytest — no `test_` prefix, for the same reason `tests/helpers.py`
is not: a helper must not look like a test.

**It refuses to emit an unsound table**, rather than emitting one and letting the guard complain:
a `|` inside a cell silently splits the row and the page then *looks* complete while being short.
"""

from __future__ import annotations

import argparse
import ast
import re
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime
from functools import lru_cache
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
REGISTER_PATH = REPO_ROOT / "REGISTER.md"
TESTS_DIR = REPO_ROOT / "tests"

BANNER = (
    "<!-- GENERATED — do not edit this file. Edit tests/register.py, then run `make register`. -->"
)

#: The longest a cited description may be before it is cut. Long enough for the longest real
#: docstring line, short enough to keep the table readable.
MAX_PINS_CHARS = 96

#: The one line in the page that is a property of *when* rather than of *what*. The guard
#: normalises it on both sides — and only it, because a second unchecked line would be a second
#: thing that could be wrong without anyone noticing.
TAKEN = re.compile(r"^_Taken .*$", re.MULTILINE)

#: `tests/test_tools.py::test_x` — one collected case, as pytest lists them.
NODE_ID = re.compile(r"^(tests/test_[a-z_0-9]+\.py)::", re.MULTILINE)
#: `553 tests collected in 0.79s` — pytest's own total, which must agree with the node ids.
REPORTED_TOTAL = re.compile(r"^(\d+) tests? collected", re.MULTILINE)


class RegisterError(Exception):
    """The register cannot be emitted as it stands."""


@dataclass(frozen=True)
class Category:
    number: int
    name: str
    meaning: str
    files: tuple[str, ...]


@dataclass(frozen=True)
class Row:
    number: str
    file: str
    tests: int
    pins: str


@dataclass(frozen=True)
class Section:
    category: Category
    rows: tuple[Row, ...]

    @property
    def tests(self) -> int:
        return sum(row.tests for row in self.rows)


@dataclass(frozen=True)
class Register:
    sections: tuple[Section, ...]
    collected: int
    taken: str

    @property
    def file_count(self) -> int:
        return sum(len(section.rows) for section in self.sections)

    @property
    def total(self) -> int:
        return sum(section.tests for section in self.sections)


#: The categories, **boundary first**. The order is the diagnostic order: a broken seam explains
#: every failure below it, so the first row that moves is the one to read.
CATEGORIES: tuple[Category, ...] = (
    Category(
        number=1,
        name="Boundary",
        meaning=(
            "The seams other components depend on. A failure here means a contract moved, and "
            "every category below it is suspect until this one is green."
        ),
        files=(
            "test_tools.py",
            "test_config.py",
            "test_trace.py",
            "test_run_log.py",
            "test_orchestrator_boundary.py",
            "test_trace_schema_doc.py",
            "test_replay.py",
        ),
    ),
    Category(
        number=2,
        name="Core",
        meaning=(
            "The loop and what it enforces — the four bounds, context assembly, the failure "
            "taxonomy. A failure here is the runtime's own behaviour, with no capability involved."
        ),
        files=(
            "test_loop.py",
            "test_budget.py",
            "test_taxonomy.py",
            "test_context.py",
            "test_structured.py",
            "test_sanitize.py",
            "test_redaction.py",
            "test_fingerprint.py",
            "test_marker_precision.py",
        ),
    ),
    Category(
        number=3,
        name="Providers",
        meaning="The model adapters. A failure here is the wire, not the loop.",
        files=("test_provider.py",),
    ),
    Category(
        number=4,
        name="Capabilities",
        meaning=(
            "The domains built on the runtime. A failure here is a configuration or a tool — "
            "the core is untouched, and deleting the capability would leave it green."
        ),
        files=("test_triage.py", "test_verify.py", "test_subagent.py", "test_judge.py"),
    ),
    Category(
        number=5,
        name="Service and operations",
        meaning=(
            "The surfaces around a run, and the tools that move a build: HTTP, revisions, rollback."
        ),
        files=("test_service.py", "test_revision.py", "test_rollback.py"),
    ),
    Category(
        number=6,
        name="Runs and evals",
        meaning=(
            "Real runs rather than constructed ones: recorded traces replayed in CI, and the "
            "live suite's own contract."
        ),
        files=("test_recorded_runs.py", "test_live_cases.py"),
    ),
    Category(
        number=7,
        name="Repo hygiene",
        meaning=(
            "The guards on the guards — the docs' claims about the code, the gate recipe, and "
            "this page. A failure here means something said is no longer true."
        ),
        files=(
            "test_repo_hygiene.py",
            "test_ci_contract.py",
            "test_env_file.py",
            "test_register.py",
            "test_notes.py",
        ),
    ),
)


def _plural(count: int, noun: str) -> str:
    """`1 file`, `2 files`. Small, and a page that says "1 files" reads as generated-and-unread."""
    return f"{count} {noun}" if count == 1 else f"{count} {noun}s"


def _cell(text: str) -> str:
    """One markdown table cell, refused if it would break the row it lives in."""
    if "|" in text:
        raise RegisterError(
            f"a cell contains '|', which silently splits the markdown row and leaves the page "
            f"looking complete while being short: {text!r}"
        )
    return text


def _truncate(line: str) -> str:
    if len(line) <= MAX_PINS_CHARS:
        return line
    return line[:MAX_PINS_CHARS].rsplit(" ", 1)[0] + "…"


@dataclass(frozen=True)
class Collection:
    """What pytest actually collected — measured, not remembered."""

    files: dict[str, int]
    total: int


@lru_cache(maxsize=1)
def collect() -> Collection:
    """Per-file case counts, from a **real collection** rather than from a remembered number.

    `AGENTS.md` says never to quote a count from memory — run it. This is that rule made
    mechanical: the register's numbers are a measurement, and the guard re-measures.

    ``-o addopts=`` clears the project's own pytest options. Without it, `pyproject.toml`'s
    ``-q`` combines with this call's ``-q`` into ``-qq``, which changes what pytest prints — so
    the parser's input would depend on a setting in another file. Clearing it makes this
    invocation the same one whatever the project does to `addopts`.

    **Two independent numbers must agree**: the node ids listed, and the total pytest reports.
    If they disagree, the parse has drifted and no count from it can be trusted.
    """
    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "pytest",
            "--collect-only",
            "-q",
            "--no-header",
            "-p",
            "no:cacheprovider",
            "-o",
            "addopts=",
        ],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise RegisterError(
            f"collection failed with exit {result.returncode}, so no count can be trusted:\n"
            f"{(result.stdout + result.stderr)[-2000:]}"
        )

    files: dict[str, int] = {}
    for name in NODE_ID.findall(result.stdout):
        key = name.removeprefix("tests/")
        files[key] = files.get(key, 0) + 1

    reported = REPORTED_TOTAL.search(result.stdout)
    if reported is None:
        raise RegisterError(
            "pytest reported no collected total, so the invocation's output has drifted and "
            "every count parsed from it is suspect"
        )
    total = int(reported.group(1))
    if sum(files.values()) != total:
        raise RegisterError(
            f"pytest reports {total} cases but listed {sum(files.values())} node ids — the parse "
            f"has drifted, so the numbers cannot be trusted"
        )
    return Collection(files=files, total=total)


def cited_summary(file: str) -> str:
    """The first line of a test module's docstring — the description the register publishes.

    Cited rather than written, because a hand-written description is a second copy of the truth
    and this project has watched a second copy drift every time.
    """
    path = TESTS_DIR / file
    if not path.is_file():
        raise RegisterError(f"the register names {file}, which does not exist")
    docstring = ast.get_docstring(ast.parse(path.read_text(encoding="utf-8")))
    if not docstring or not docstring.strip():
        raise RegisterError(
            f"{file} has no module docstring, so the register has nothing to cite for it. A "
            f"test module that does not say what it pins cannot be listed honestly."
        )
    return _cell(_truncate(docstring.strip().splitlines()[0].strip()))


def test_files_on_disk() -> set[str]:
    return {path.name for path in TESTS_DIR.glob("test_*.py")}


def build() -> Register:
    """Assemble the register, refusing anything unsound."""
    collection = collect()
    counts = collection.files
    categorised = [file for category in CATEGORIES for file in category.files]

    duplicated = sorted({file for file in categorised if categorised.count(file) > 1})
    if duplicated:
        raise RegisterError(f"these files are in more than one category: {duplicated}")

    missing = sorted(set(categorised) - test_files_on_disk())
    if missing:
        raise RegisterError(f"the register names files that do not exist: {missing}")

    uncategorised = sorted(test_files_on_disk() - set(categorised))
    if uncategorised:
        raise RegisterError(
            f"these test files have no category: {uncategorised}. Every file belongs to exactly "
            f"one, so that a failure is pinpointed by where it appears rather than by reading it."
        )

    uncollected = sorted(set(categorised) - set(counts))
    if uncollected:
        raise RegisterError(
            f"pytest collected no tests from {uncollected}. Either the file is empty or it failed "
            f"to import — and a file that cannot be collected is a suite that is quietly smaller."
        )

    sections = tuple(
        Section(
            category=category,
            rows=tuple(
                Row(
                    number=f"{category.number}.{index}",
                    file=file,
                    tests=counts[file],
                    pins=cited_summary(file),
                )
                for index, file in enumerate(category.files, start=1)
            ),
        )
        for category in CATEGORIES
    )

    empty = [section.category.name for section in sections if not section.rows]
    if empty:
        raise RegisterError(f"these categories have no rows: {empty}")

    register = Register(
        sections=sections,
        collected=collection.total,
        taken=datetime.now().astimezone().strftime("%Y-%m-%d %H:%M %Z"),
    )
    if register.total != register.collected:
        raise RegisterError(
            f"the rows sum to {register.total} cases and pytest collected {register.collected}. "
            f"The page would state a number that its own rows contradict."
        )
    return register


def render(register: Register) -> str:
    lines = [
        "# REGISTER.md — the test suite, by category",
        "",
        BANNER,
        "",
        "**This page is a projection, not a summary.** Every count is measured from a real",
        "collection and every description is the first line of the file's own docstring — cited,",
        "never paraphrased. `tests/test_register.py` re-derives both and fails when the page and",
        "the suite disagree, so the page cannot rot quietly.",
        "",
        "Categories are ordered so a failure is pinpointed by the **first** row that moves. The",
        "boundary comes first: a broken seam explains every failure below it, and a run of",
        "failures in one category is one defect, not many.",
        "",
        f"**{register.file_count} files · {register.total} cases.**",
        "",
        "## The categories",
        "",
        "| # | category | files | cases | a failure here means |",
        "|---|---|---|---|---|",
    ]
    for section in register.sections:
        lines.append(
            f"| {section.category.number} | {section.category.name} | {len(section.rows)} | "
            f"{section.tests} | {_cell(section.category.meaning)} |"
        )
    lines.append("")

    for section in register.sections:
        lines += [
            f"## {section.category.number}. {section.category.name}",
            "",
            f"{section.category.meaning} **{_plural(len(section.rows), 'file')}, "
            f"{_plural(section.tests, 'case')}.**",
            "",
            "| # | file | cases | what it pins (cited from the file's docstring) |",
            "|---|---|---|---|",
            *[
                f"| {row.number} | `tests/{row.file}` | {row.tests} | {row.pins} |"
                for row in section.rows
            ],
            "",
        ]

    lines += [
        "## When this snapshot was taken",
        "",
        f"_Taken {register.taken}. Not checked — it says when, not what._",
        "",
        "**No revision is recorded here, deliberately.** A SHA written into a file goes stale the",
        "moment the branch carrying it is rebase-merged: the merge rewrites the commit, and the",
        "file then points at something nobody can check out. The date says *when*; `git log` says",
        "which commit touched this file, and git is the authority on that rather than a copy of",
        "it. `tests/test_register.py` fails if a revision-shaped token appears in this page again.",
        "",
        "## Adding a test file",
        "",
        "A new `tests/test_*.py` fails the suite until it is given a category in",
        "`tests/register.py`, and the numbers fail until the page is regenerated. That is",
        "deliberate: an uncategorised file is a failure nobody knows how to read.",
        "",
    ]
    return "\n".join(lines)


def normalise(text: str) -> str:
    """Everything in the page except what is a property of *when*."""
    return TAKEN.sub("_Taken <when>_", text)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate REGISTER.md from the test suite.")
    parser.add_argument("--write", action="store_true", help="write the file")
    parser.add_argument("--check", action="store_true", help="exit non-zero if the file is stale")
    args = parser.parse_args(argv)

    try:
        text = render(build())
    except RegisterError as exc:
        print(f"register: {exc}", file=sys.stderr)
        return 2

    if args.check:
        current = REGISTER_PATH.read_text(encoding="utf-8") if REGISTER_PATH.is_file() else ""
        if normalise(current) != normalise(text):
            print(
                "REGISTER.md is stale or missing — run `make register` and commit the result",
                file=sys.stderr,
            )
            return 1
        return 0

    if args.write:
        REGISTER_PATH.write_text(text, encoding="utf-8")
        print(f"wrote {REGISTER_PATH.relative_to(REPO_ROOT)}")
        return 0

    print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
