"""The generator for `NOTES.md` — every markdown file, with the claim it leads with.

**The page quotes; it never paraphrases.** A hand-written summary of forty documents would be
forty second copies of the truth, and this project has watched a second copy drift every time it
has made one. So each row carries a sentence *from the file itself*:

* a **decision** states its own claim in its heading — `# 0031 — The spend is in the record` —
  and that heading is what gets quoted, stripped of its number. Nothing to write, nothing to
  drift.
* a **guide** does not, so the sentence is chosen by hand and **verified verbatim** by
  `tests/test_notes.py`. Choosing it is judgement; the guard is what stops it becoming a
  paraphrase.

The generator refuses rather than emitting an unsound page: a file with no row, a row with no
file, a quote that is not in the file it claims, or a `|` that would split the table and leave
the page looking complete while being short.

This module is a script, not a test, and is not collected by pytest.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

from runtime.config import load_env_file

REPO_ROOT = Path(__file__).resolve().parent.parent
NOTES_PATH = REPO_ROOT / "NOTES.md"

BANNER = (
    "<!-- GENERATED — do not edit this file. Edit scripts/derive_notes.py, then run `make notes`. "
    "-->"
)

#: The page cannot distil itself, and a row quoting this file would be a claim about a claim.
SELF = "NOTES.md"

#: A decision's heading: `# 0031 — The spend is in the record`.
DECISION_HEADING = re.compile(r"^# (\d{4}) — (.+)$", re.M)
H1 = re.compile(r"^# (.+)$", re.M)


class NotesError(Exception):
    """The page cannot be emitted as it stands."""


@dataclass(frozen=True)
class Group:
    number: int
    name: str
    short: str
    meaning: str
    files: tuple[str, ...]


@dataclass(frozen=True)
class Row:
    number: str
    path: str
    point: str


@dataclass(frozen=True)
class Section:
    group: Group
    rows: tuple[Row, ...]


@dataclass(frozen=True)
class Notes:
    sections: tuple[Section, ...]

    @property
    def total(self) -> int:
        return sum(len(section.rows) for section in self.sections)


#: The claim each guide leads with, quoted from the file. The guard checks every one is verbatim,
#: so a rewording here fails the suite rather than quietly becoming what the document "says".
LEAD_CLAIMS: dict[str, str] = {
    "AGENTS.md": "**The core loop contains no domain logic and no provider-specific code.**",
    "AGENTS_LEARNING.md": (
        "What this project has taught us: the surprises, the mistakes, and the questions still "
        "open."
    ),
    "README.md": (
        '"General purpose" means **the runtime is generic and every capability is a '
        "configuration.**"
    ),
    "REFERENCE.md": (
        "The durable knowledge for working here: the conventions the code does not show you, and "
        "the mistakes that have already been paid for."
    ),
    "REGISTER.md": "**This page is a projection, not a summary.**",
    "docs/architecture.md": "The runtime is generic; every capability is a configuration.",
    "docs/roadmap.md": "Where this is going, in dependency order.",
    "docs/trace-schema.md": (
        "It is the only record, and **replay reconstructs a run from it alone** — so this document "
        "describes a contract, not a log format."
    ),
}

GROUPS: tuple[Group, ...] = (
    Group(
        number=1,
        name="The root documents",
        short="root documents",
        meaning=(
            "The five documents at the root. If you read nothing else, these are what to read, and "
            "the order matters: `AGENTS.md` is the spec and wins."
        ),
        files=("AGENTS.md", "AGENTS_LEARNING.md", "README.md", "REFERENCE.md", "REGISTER.md"),
    ),
    Group(
        number=2,
        name="The guides",
        short="guides",
        meaning="The three documents under `docs/` that are not decisions.",
        files=("docs/architecture.md", "docs/roadmap.md", "docs/trace-schema.md"),
    ),
    Group(
        number=3,
        name="The decision record",
        short="decisions",
        meaning=(
            "One row per decision, quoting the heading each one states its claim in. The record is "
            "append-only and read by number; this is its table of contents."
        ),
        files=(),  # filled from the filesystem — a decision is any `docs/decisions/*.md`
    ),
)


def _cell(text: str) -> str:
    if "|" in text:
        raise NotesError(
            f"a cell contains '|', which silently splits the markdown row and leaves the page "
            f"looking complete while being short: {text!r}"
        )
    return text


def _normalise(text: str) -> str:
    """Whitespace-collapsed, so a quote may span the hard-wrapped lines of the source."""
    return re.sub(r"\s+", " ", text).strip()


def documents() -> list[str]:
    """Every markdown file the page must account for, relative to the repository root."""
    found = [p.name for p in sorted(REPO_ROOT.glob("*.md")) if p.name != SELF]
    found += [str(p.relative_to(REPO_ROOT)) for p in sorted((REPO_ROOT / "docs").rglob("*.md"))]
    return found


def decisions() -> list[str]:
    return [p for p in documents() if p.startswith("docs/decisions/")]


def decision_point(path: str) -> str:
    """A decision's own claim: its heading, minus the number."""
    text = (REPO_ROOT / path).read_text(encoding="utf-8")
    match = DECISION_HEADING.search(text)
    if match is None:
        raise NotesError(
            f"{path} has no `# NNNN — <claim>` heading, so the page has nothing of its own to "
            f"quote. A decision that does not state its claim in its heading cannot be listed "
            f"honestly."
        )
    return _cell(match.group(2).strip())


def guide_point(path: str) -> str:
    """A guide's claim, quoted — and checked, here, that the quote is really in the file."""
    point = LEAD_CLAIMS.get(path)
    if point is None:
        raise NotesError(
            f"{path} has no lead claim in LEAD_CLAIMS. Every document needs one, or the page would "
            f"be a list of filenames."
        )
    if _normalise(point) not in _normalise((REPO_ROOT / path).read_text(encoding="utf-8")):
        raise NotesError(
            f"the claim recorded for {path} is not in the file — it has been reworded, which is "
            f"the one thing this page exists not to do: {point!r}"
        )
    return _cell(point)


def _point_for(path: str) -> str:
    """A decision quotes its own heading; a guide quotes a sentence chosen by hand."""
    if path.startswith("docs/decisions/"):
        return decision_point(path)
    return guide_point(path)


def build() -> Notes:
    """Assemble the page, refusing anything unsound."""
    on_disk = set(documents())
    listed = [f for group in GROUPS for f in group.files]
    listed += decisions()

    missing = sorted(set(listed) - on_disk)
    if missing:
        raise NotesError(f"the page names files that do not exist: {missing}")

    unlisted = sorted(on_disk - set(listed))
    if unlisted:
        raise NotesError(
            f"these markdown files have no row: {unlisted}. Every document is accounted for, so "
            f"that a new one cannot be written and forgotten."
        )

    sections: list[Section] = []
    for group in GROUPS:
        files = decisions() if group.name == "The decision record" else list(group.files)
        if not files:
            raise NotesError(f"group {group.number} ({group.name}) has no rows")
        rows = tuple(
            Row(
                number=f"{group.number}.{index}",
                path=path,
                point=_point_for(path),
            )
            for index, path in enumerate(files, start=1)
        )
        sections.append(Section(group=group, rows=rows))
    return Notes(sections=tuple(sections))


def render(notes: Notes) -> str:
    counts = " · ".join(f"{len(s.rows)} {s.group.short}" for s in notes.sections)
    lines = [
        "# NOTES.md — the documentation, distilled",
        "",
        BANNER,
        "",
        "**Every markdown file in this repository, with the claim it leads with — quoted, never",
        "paraphrased.** A decision states its own claim in its heading, so that is what is quoted.",
        "A guide does not, so its claim is chosen by hand and checked verbatim. Either way the",
        "words are the document's, which is what makes this a page you can trust rather than a",
        "summary that drifts.",
        "",
        "`tests/test_notes.py` fails if a document is missing from the page, if a quotation is no",
        "longer in the file it cites, or if the page does not match a fresh render. So: **do not",
        "edit this file** — edit `scripts/derive_notes.py` and run `make notes`.",
        "",
        f"**{notes.total} documents** — {counts}.",
        "",
    ]
    for section in notes.sections:
        lines += [
            f"## {section.group.number}. {section.group.name}",
            "",
            section.group.meaning,
            "",
            "| # | file | the claim it leads with, in its own words |",
            "|---|---|---|",
            *[f"| {row.number} | `{row.path}` | {row.point} |" for row in section.rows],
            "",
        ]
    lines += [
        "## What this page is not",
        "",
        "- **Not a decision record.** The rows point at `docs/decisions/`; the reasoning lives",
        "  there and nowhere else. Nothing here settles anything.",
        "- **Not a summary of the code.** `REGISTER.md` covers the test suite; this covers the",
        "  prose.",
        "- **Not complete about any one document.** A row is the claim a file leads with, not what",
        "  it contains. Read the file for the rest.",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    # Every script in this repository loads it, whether or not it needs a key today: a tool run by
    # hand should see the same environment as the rest of them. `tests/test_env_file.py` requires
    # this call from every `__main__` file outside `tests/`, and that rule is deliberately simple —
    # narrowing it to "files that import the runtime" would let a future script that reads a key
    # directly slip past it.
    load_env_file()
    parser = argparse.ArgumentParser(description="Generate NOTES.md from the documentation.")
    parser.add_argument("--write", action="store_true", help="write the file")
    parser.add_argument("--check", action="store_true", help="exit non-zero if the file is stale")
    args = parser.parse_args(argv)

    try:
        text = render(build())
    except NotesError as exc:
        print(f"notes: {exc}", file=sys.stderr)
        return 2

    if args.check:
        current = NOTES_PATH.read_text(encoding="utf-8") if NOTES_PATH.is_file() else ""
        if current != text:
            print("NOTES.md is stale or missing — run `make notes`", file=sys.stderr)
            return 1
        return 0

    if args.write:
        NOTES_PATH.write_text(text, encoding="utf-8")
        print(f"wrote {NOTES_PATH.relative_to(REPO_ROOT)}")
        return 0

    print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
